# Name of website
url: "https://vksz.io"
title: vksz.io
author: vakesz
avatar: "/assets/img/avatar.png"
round-avatar: true
date_format: "%B %-d, %Y"
rss-description: This website is a virtual proof that I'm awesome

###############################################
# --- List of links in the navigation bar --- #
###############################################

navbar-links:
  Posts: "index"
  About Me: "aboutme"
#  Menu:
#    - A-Submenu: "#"

#####################################
# --- Footer social media links --- #
#####################################

social-network-links:
  github: vakesz
  twitter: vakeszqe
  email: "hello@vksz.io"
  linkedin: gabor-pinkova
  twitch: vakesz
#  patreon: yourname
#  youtube: yourname
#  stackoverflow: "yourname"
#  instagram: yourname
#  steam: vakesz
#  telegram: yourname
#  mastodon: instance.url/@username
#  discord: invite/invite_code or users/userid 
#  hackerrank: yourname

###########################
# --- General options --- #
###########################

share-links-active:
  twitter: true
  facebook: true
  linkedin: true
  vk: false

url-pretty: "vksz.io"
excerpt_length: 50
feed_show_excerpt: true
feed_show_tags: true
post_search: true
edit_page_button: false
navbar-var-length: false
keywords: "vakesz,vksz,blog"

######################################
# --- Colours / background image --- #
######################################
navbar-col: "#2E2E2E"
navbar-text-col: "#FFF"
navbar-border-col: "#2E2E2E"
page-col: "#323232"
text-col: "#FFF"
link-col: "#FFCC00"
hover-col: "#FFCC00"
footer-col: "#2E2E2E"
footer-text-col: "#FFF"
footer-link-col: "#585858"
footer-hover-col: "#000"
mobile-theme-col: "#2E2E2E"

#################################
# --- Web Analytics Section --- #
#################################
cloudflare_analytics: "36c7a9de33214d80a4b92b22678acb0f"

####################
# --- Comments --- #
####################
disqus: "vksz"

################
# --- Misc --- #
################
timezone: "Europe/Budapest"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month/:title/
paginate: 5

kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
  -
    scope:
      path: "" # any file that's not a post will be a "page" layout by default
    values:
      layout: "page"

# Exclude these files from production site
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-minifier
  - jekyll-seo-tag