# Name of website
url: "https://vksz.io" # the base hostname & protocol for your site
title: vksz.io
author: vakesz
avatar: "/assets/img/avatar.png"
round-avatar: true
#title-img: "/assets/img/avatar-icon.png"
date_format: "%B %-d, %Y"
rss-description: This website is a virtual proof that I'm awesome

###############################################
# --- List of links in the navigation bar --- #
###############################################

navbar-links:
  Posts: "index"
  About Me: "aboutme"
#  Menu:
#    - A-Submenu: "#"

#####################################
# --- Footer social media links --- #
#####################################

# Select the social network links that you want to show in the footer.
# Uncomment the links you want to show and add your information to each one.
social-network-links:
  github: vakesz
  twitter: vakeszqe
  email: "hello@vksz.io"
  linkedin: gabor-pinkova
  twitch: vakesz
#  patreon: yourname
#  youtube: yourname
#  medium: yourname
#  reddit: yourname
#  facebook: yourname
#  xing: yourname
#  stackoverflow: "yourname"
#  snapchat: yourname
#  instagram: yourname
#  spotify: vakesz
#  telephone: yourname
#  steam: vakesz
#  yelp: yourname
#  telegram: yourname
#  calendly: yourname
#  mastodon: instance.url/@username
#  google-scholar: your google scholar
#  discord: invite/invite_code or users/userid 
#  hackerrank: yourname

###########################
# --- General options --- #
###########################

share-links-active:
  twitter: true
  facebook: true
  linkedin: true
  vk: false

url-pretty: "vksz.io"
excerpt_length: 50
feed_show_excerpt: true
feed_show_tags: true
post_search: true
edit_page_button: false
navbar-var-length: false
keywords: "vakesz,vksz,blog"

######################################
# --- Colours / background image --- #
######################################
navbar-col: "#2E2E2E"
navbar-text-col: "#FFF"
navbar-border-col: "#2E2E2E"
page-col: "#323232"
text-col: "#FFF"
link-col: "#FFCC00"
hover-col: "#FFCC00"
footer-col: "#2E2E2E"
footer-text-col: "#FFF"
footer-link-col: "#585858"
footer-hover-col: "#000"
mobile-theme-col: "#2E2E2E"

#################################
# --- Web Analytics Section --- #
#################################
cloudflare_analytics: "36c7a9de33214d80a4b92b22678acb0f"

####################
# --- Comments --- #
####################

# To use Disqus comments, sign up to https://disqus.com and fill in your Disqus shortname (NOT the userid)
disqus: "vksz"

# To use Facebook Comments, create a Facebook app and fill in the Facebook App ID
#fb_comment_id: ""

# To use CommentBox, sign up for a Project ID on https://commentbox.io
#commentbox: "" # Project ID, e.g. "5694267682979840-proj"

# To use Utterances comments: (0) uncomment the following section, (1) fill in
# "repository" (make sure the repository is public), (2) Enable Issues in your repository,
# (3) Install the Utterances app in your repository https://github.com/apps/utterances
# See more details about the parameters below at https://utteranc.es/
#utterances:
#  repository: # GitHub username/repository eg. "daattali/beautiful-jekyll"
#  issue-term: title   # Mapping between blog posts and GitHub issues
#  theme: github-light # Utterances theme
#  label: blog-comments # Label that will be assigned to GitHub Issues created by Utterances

# To use Staticman comments, uncomment the following section. You may leave the reCaptcha
# section commented if you aren't using reCaptcha for spam protection. 
# Using Staticman requires advanced knowledge, please consult 
# https://github.com/eduardoboucas/staticman/ and https://staticman.net/ for further 
# instructions. For any support with staticman please direct questions to staticman and 
# not to BeautifulJekyll.
#staticman:
#  repository : # GitHub username/repository eg. "daattali/beautiful-jekyll"
#  branch     : master # If you're not using `master` branch, then you also need to update the `branch` parameter in `staticman.yml`
#  endpoint   : # URL of your deployment, with a trailing slash eg. "https://<your-api>/v3/entry/github/"
#  reCaptcha:   # (optional, set these parameters in `staticman.yml` as well) 
#    siteKey  : # You need to apply for a site key on Google
#    secret   : # Encrypt your password by going to https://<your-own-api>/v3/encrypt/<your-site-secret>

# To use giscus comments:
# (0) Uncomment the following giscus section, (1) Enable Discussions in your GitHub repository, 
# (2) Install the giscus app in your repository (details at https://giscus.app),
# (3) Fill in *all* the parameters below 
# See more details about giscus and each of the following parameters at https://giscus.app
#giscus:
#  hostname: giscus.app # Replace with your giscus instance's hostname if self-hosting
#  repository: # GitHub username/repository eg. "daattali/beautiful-jekyll"
#  repository-id: # ID of your repository, retrieve this info from https://giscus.app
#  category: Announcements # Category name of your GitHub Discussion posts
#  category-id: # ID of your category, retrieve this info from https://giscus.app
#  mapping: pathname
#  reactions-enabled: 1
#  emit-metadata: 0
#  theme: light

################
# --- Misc --- #
################
timezone: "Europe/Budapest"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month/:title/
paginate: 5

kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
  -
    scope:
      path: "" # any file that's not a post will be a "page" layout by default
    values:
      layout: "page"

# Exclude these files from production site
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-email-protect
  - jekyll-sitemap